dle/data/models.py, dle/docker-compose.yml, dle/search/mappings/productsection.json, dle/search/static/search/styles.css, dle/search/templates/search/elastic/search.html, dle/search/urls.py, dle/search/views.py, dle/static/search/search.js, docs/kibana_examples.txt
Once setup, go to `http://localhost:8000/search/es_search`
You should see the following image...
=> Es searchkit

dle/data/management/commands/load_ema_data.py, dle/data/management/commands/load_tga_data.py, dle/data/management/commands/pdf_parsing_helper.py, dle/requirements.txt
Update EMA & TGA scripts. 
Replace the current parsing approach with Caleb's approach. Parse for all sections instead of just 9
=> Update EMA & TGA parsing code

README.md, dle/search/templates/search/base.html, dle/search/templates/search/header.html, dle/search/templates/search/search_landing/search_landing.html, dle/users/templates/users/register.html, docs/readme.md
Changes name to SearchRx in all instances mentioned in the application or in documentation.
=> Change name to searchrx

dle/search/static/search/es_search.js
=> Results link to name and query

dle/search/static/search/es_search.js, dle/search/static/search/styles.css, dle/search/templates/search/elastic/search.html
A few simple tweaks to improve look and feel of the search results page.
See screenshot below.
=> Simple ux tweaks

dle/search/static/search/es_search.js, dle/search/static/search/styles.css, dle/search/templates/search/elastic/search.html, dle/search/templates/search/search_landing/search_form.html, dle/search/templates/search/search_landing/search_form_text_input.html, dle/search/templates/search/search_results/results_search_input.html
Homepage now is simpler without the filters and when you search, it takes you to our searchkit page. See video below. 
https://user-images.githubusercontent.com/310231/229972587-820425e3-b8ea-436e-997e-1c728ba381f1.mp4
=> New homepage

dle/search/static/search/es_search.js, dle/search/static/search/styles.css, dle/search/templates/search/elastic/search.html
Adds logic to take user to comparison page. 
Compare button is hidden unless 2 or 3 labels are selected. 
Purposefully didn't style anything so @lucyzsunshine can focus on that task. 
Demo video below... 
https://share.getcloudapp.com/d5ugggnv#
=> Adds compare results functionality

dle/data/templates/data/single_label.html
Branched off of the scroll PR so that code is in here also 🤷
=> Makes download original source document hard to miss DL-198

dle/data/templates/data/single_label.html
Gets jump to specific sections working as expected... 
See demo: https://share.getcloudapp.com/v1uPnRKG
=> Fixes scroll to that was scrolling too far due to the header

dle/search/views.py
fixed bug preventing cloud deployment
=> fixed duplicate endpoint preventing cloud deployment

.github/workflows/auto_deploy.yml, aws_setup.sh
workflow updates ECR deployment
=> Auto deploy ecs

dle/elastic-http-deploy.yaml
compose file for elastic deployment on ec2 with http
=> added elastic http deploy file

dle/aws_setup.sh
connection was breaking on auto-deploy due to https. set up script now configures http
=> Updated aws setup script to use http

dle/data/management/commands/load_fda_data.py
It was showing array of string instead of string (e.g., ['abc'] instead of abc) for product name, section text, etc
=> Fix FDA loading script

dle/.env.test-example, dle/Dockerfile, dle/Dockerfile.dev, dle/Dockerfile.tests, dle/entrypoint, docs/readme.md
- Updates Python Deb version from buster to bullseye
- Uses PSQL 14 instead of 11 - dump file is 14 and 11 couldn't read it
- Update docs
=> Fix the pg_restore command and PSQL version

dle/dle/settings.py
=> fixes csrf

dle/data/management/commands/vectorize.py
Was not allowing just FDA for vectorization
=> Fix vectorize command typo

dle/search/templates/search/elastic/search.html
=> Fixes wonkiness with search results

dle/data/management/commands/load_fda_data.py
https://cscie599-drug-labels.atlassian.net/browse/DL-230
=> Filter FDA to only use NDA labels

dle/aws_setup.sh
setup script fixed to pull correct param names
=> fixed setup script

.github/workflows/infra_deploy.yml, cfn/deploy_ec2.yaml, cfn/deploy_ecr.yaml, cfn/deploy_ecs.yaml, cfn/deploy_lb.yaml, cfn/deploy_rds.yaml, cfn/deploy_s3.yaml, cfn/deploy_vpc.yaml
Cloudformation scripts to provision AWS env
=> Alex infra deploy

dle/data/management/commands/load_ema_data.py, dle/data/management/commands/load_fda_data.py, dle/data/management/commands/load_hc_data.py, dle/data/management/commands/load_tga_data.py, dle/data/management/commands/pdf_parsing_helper.py
XML is expected for US labels, and PDF for others
=> Add custom label support

dle/data/management/commands/remove_non_nda_dls_fda.py
Need to check that it is building a valid list.
Looks like this is getting killed on the ECS task - not enough RAM to load one of the JSON files
=> Remove non-NDA OpenFDA DLs

.github/workflows/infra_deploy.yml
Only run on changes to the CFN dir
=> Fix Github Actions syntax

cfn/deploy_ec2.yaml, dle/elastic_setup.sh
added vars for elastic deployment
=> added elastic deploy on aws

.github/workflows/infra_deploy.yml, cfn/deploy_ecs.yaml
updated ssm var names in workflow.
removed commented out vars in ecs_deploy script
=> updated ssm var names in workflow, removed commented out vars in ecs_deploy script
